name: Minecraft PlayTime

on:
  schedule:
    - cron:  '00 06 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Logs Download
      run: |
        sudo apt install sshpass
        sshpass -p ${PASSWORD} scp -o StrictHostKeyChecking=no -r ${USERNAME}@${SERVER_IP}:${FILE_PATH} ./
      env:
        SERVER_IP: ${{secrets.SERVER_IP}}
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        FILE_PATH: ${{secrets.FILE_PATH}}

    - name: gzip logs
      run: |
        gzip -d logs/*.gz
        rm logs/latest.log

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: Run Go
      run: |
        go get
        go run main.go
      env:
        USER1: ${{secrets.USER1}}
        USER2: ${{secrets.USER2}}
        USER3: ${{secrets.USER3}}
        USER4: ${{secrets.USER4}}
        USER5: ${{secrets.USER5}}
        USER_NAME1: ${{secrets.USER_NAME1}}
        USER_NAME2: ${{secrets.USER_NAME2}}
        USER_NAME3: ${{secrets.USER_NAME3}}
        USER_NAME4: ${{secrets.USER_NAME4}}
        USER_NAME5: ${{secrets.USER_NAME5}}
        WEBHOOK: ${{secrets.WEBHOOK}}
