name: Go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Logs Download
      run: |
        sudo apt install sshpass
        sshpass -p ${PASSWORD} scp -o StrictHostKeyChecking=no -r ${USERNAME}@${SERVER_IP}:${FILE_PATH} ./
      env:
        SERVER_IP: ${{secrets.SERVER_IP}}
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        FILE_PATH: ${{secrets.FILE_PATH}}

    - name: gzip logs
      run: |
        gzip -d logs/*.gz
        rm latest.log
        
    - name: testLogs
      run: ls -l logs/

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
