name: Go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "/opt/minecraft_server/logs"
        target: "./"

    - name: Test
      run: ls -l

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
