name: Go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run sh
      run: |
        sudo apt-get install expect
        sh ./.github/ssh.sh '${SERVER_IP}' '${PASSWORD}'
        sleep 5
      env:
        SERVER_IP: ${{secrets.SERVER_IP}}
        PASSWORD: ${{secrets.PASSWORD}}

    - name: Test
      run: ls -l

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
